// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("StringBuffer")>]
[<assembly: AssemblyProductAttribute("StringBuffer")>]
[<assembly: AssemblyVersionAttribute("1.0.2")>]
[<assembly: AssemblyMetadataAttribute("ReleaseDate","2024-11-15T00:00:00.0000000+00:00")>]
[<assembly: AssemblyFileVersionAttribute("1.0.2")>]
[<assembly: AssemblyInformationalVersionAttribute("1.0.2")>]
[<assembly: AssemblyMetadataAttribute("ReleaseChannel","release")>]
[<assembly: AssemblyMetadataAttribute("GitHash","4a937e6a9c4ae145986a1c30c6f7b3979c849b6e")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "StringBuffer"
    let [<Literal>] AssemblyProduct = "StringBuffer"
    let [<Literal>] AssemblyVersion = "1.0.2"
    let [<Literal>] AssemblyMetadata_ReleaseDate = "2024-11-15T00:00:00.0000000+00:00"
    let [<Literal>] AssemblyFileVersion = "1.0.2"
    let [<Literal>] AssemblyInformationalVersion = "1.0.2"
    let [<Literal>] AssemblyMetadata_ReleaseChannel = "release"
    let [<Literal>] AssemblyMetadata_GitHash = "4a937e6a9c4ae145986a1c30c6f7b3979c849b6e"
