// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("StringBuffer")>]
[<assembly: AssemblyProductAttribute("StringBuffer")>]
[<assembly: AssemblyVersionAttribute("1.0.1")>]
[<assembly: AssemblyMetadataAttribute("ReleaseDate","2024-03-29T00:00:00.0000000+00:00")>]
[<assembly: AssemblyFileVersionAttribute("1.0.1")>]
[<assembly: AssemblyInformationalVersionAttribute("1.0.1")>]
[<assembly: AssemblyMetadataAttribute("ReleaseChannel","release")>]
[<assembly: AssemblyMetadataAttribute("GitHash","0919ca01c8295a5770a1508af90e5f93b2c4e851")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "StringBuffer"
    let [<Literal>] AssemblyProduct = "StringBuffer"
    let [<Literal>] AssemblyVersion = "1.0.1"
    let [<Literal>] AssemblyMetadata_ReleaseDate = "2024-03-29T00:00:00.0000000+00:00"
    let [<Literal>] AssemblyFileVersion = "1.0.1"
    let [<Literal>] AssemblyInformationalVersion = "1.0.1"
    let [<Literal>] AssemblyMetadata_ReleaseChannel = "release"
    let [<Literal>] AssemblyMetadata_GitHash = "0919ca01c8295a5770a1508af90e5f93b2c4e851"
