// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("StringBuffer")>]
[<assembly: AssemblyProductAttribute("StringBuffer")>]
[<assembly: AssemblyVersionAttribute("1.0.0")>]
[<assembly: AssemblyMetadataAttribute("ReleaseDate","2024-03-29T00:00:00.0000000+00:00")>]
[<assembly: AssemblyFileVersionAttribute("1.0.0")>]
[<assembly: AssemblyInformationalVersionAttribute("1.0.0")>]
[<assembly: AssemblyMetadataAttribute("ReleaseChannel","release")>]
[<assembly: AssemblyMetadataAttribute("GitHash","9f0176d54dcffb1ece283d12d5fd4e5faf9617b9")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "StringBuffer"
    let [<Literal>] AssemblyProduct = "StringBuffer"
    let [<Literal>] AssemblyVersion = "1.0.0"
    let [<Literal>] AssemblyMetadata_ReleaseDate = "2024-03-29T00:00:00.0000000+00:00"
    let [<Literal>] AssemblyFileVersion = "1.0.0"
    let [<Literal>] AssemblyInformationalVersion = "1.0.0"
    let [<Literal>] AssemblyMetadata_ReleaseChannel = "release"
    let [<Literal>] AssemblyMetadata_GitHash = "9f0176d54dcffb1ece283d12d5fd4e5faf9617b9"
